import Head from 'next/head'
import styles from '../styles/Home.module.css'
import ContactCard from '../components/contactCard'
import Header from '../components/Header'
import Footer from '../components/Footer'
import ErrorMessage from '../components/Error'
import Link from 'next/link'
import { useState, useEffect } from 'react'


const DUMMY_DATA =[
  {
    id: '0',
    name: 'Divesh kumar Singh',
    type: 'Office',
    phone: '9205029076',
    isWhatsApp: 'true',
    photo: "https://firebasestorage.googleapis.com/v0/b/invedus-divesh.appspot.com/o/files%2Fphoto.jpeg?alt=media&token=967207d5-e8bd-4bc4-a409-03cabeffbc8e"
  },
  {
    id: '1',
    name: 'Prashant Verma',
    type: 'Personal',
    phone: '9204455544',
    isWhatsApp: 'false',
    photo: "https://firebasestorage.googleapis.com/v0/b/invedus-divesh.appspot.com/o/files%2Fphoto.jpeg?alt=media&token=967207d5-e8bd-4bc4-a409-03cabeffbc8e"

  },
  {
    id: '2',
    name: 'Vaibhav Panwar',
    type: 'Office',
    phone: '9347814526',
    isWhatsApp: 'true',
    photo: "https://firebasestorage.googleapis.com/v0/b/invedus-divesh.appspot.com/o/files%2Fphoto.jpeg?alt=media&token=967207d5-e8bd-4bc4-a409-03cabeffbc8e"

  },
  {
    id: '3',
    name: 'Chandler Meurel Bing',
    type: 'Personal',
    phone: '9205029076',
    isWhatsApp: 'false',
    photo: "https://firebasestorage.googleapis.com/v0/b/invedus-divesh.appspot.com/o/files%2Fphoto.jpeg?alt=media&token=967207d5-e8bd-4bc4-a409-03cabeffbc8e"

  },
  {
    id: '4',
    name: 'Joshep Tribiani',
    type: 'Office',
    phone: '9205029076',
    isWhatsApp: 'true',
    photo: "https://firebasestorage.googleapis.com/v0/b/invedus-divesh.appspot.com/o/files%2Fphoto.jpeg?alt=media&token=967207d5-e8bd-4bc4-a409-03cabeffbc8e"
  }
]



export default function Home() {
  
  const [data, setData] = useState([])

  // To be used in form component
  // useEffect(() => {
  //   localStorage.setItem('contacts', JSON.stringify(DUMMY_DATA));
  // }, [data]);

  useEffect(() => {
    const contacts = JSON.parse(localStorage.getItem('contacts'));
    if (contacts) {
    setData(contacts);
    }
  }, []);

  return (

    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header/>

        <div className="grid sm:grid-cols-1 md:grid-cols-1 lg:grid-cols-2 xl:grid-cols-4 2xl:grid-cols-4 gap-5 pt-20 px-5">
        {console.log(data)}
          {data.length !==0 ? data.map((contact)=>(
            <ContactCard 
            key={contact.id}
            name = {contact.name}
            type = {contact.type}
            phone = {contact.phone}
            isWhatsApp = {contact.isWhatsApp}
            photo= {contact.photo}
            />
          )) : <div className='text-xl '><ErrorMessage message="NO CONTACT FOUND"/> <div className=''><Link href='/AddContactsPage' className='border rounded-xl px-2 text-lg'>Add Contacts</Link></div></div>
          }
        </div>
      </main>

      <Footer/>
    </div>
  )
}
